{
 "title": "My nodexporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_ticks_count,instance)"
    }
   },
   {
    "name": "iface",
    "query": {
     "query": "label_values(network_io_total{instance=\"$instance\"},iface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (type) (rate(node_cpu_ticks_count{instance=\"$instance\"}[$__rate_interval]))/1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_ticks_count{instance=\"$instance\",type=\"user\"}[$__rate_interval])/10",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "memory_summary{instance=\"$instance\"}/1024/1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_summary{instance=\"$instance\", type=~\"(?i)^(mem).+$\"}/1024/1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_summary{instance=\"$instance\", type=~\"(?i)^(mem).+$\"}/1024/1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top3 ram",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 2, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "topk(3,memory_usage{instance=\"$instance\", type=\"Pss\"}/1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "memory_summary{instance=\"$instance\", type=~\"(?i)^(swap).+$\"}/1024/1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Swap free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_summary{instance=\"$instance\", type=~\"(?i)^(swap).+$\"}/1024/1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RAM usage by process",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{instance=\"$instance\", instance=\"$instance\",type=\"Pss\"}/1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM (Rss) usage by process",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{instance=\"$instance\", type=\"Rss\"}/1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap usage by process",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{instance=\"$instance\", type=\"SwapPss\"}/1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top3 swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 2, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "topk(3,memory_usage{instance=\"$instance\", type=\"SwapPss\"}/1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network transmission errors / drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (iface) (rate(network_io_total{instance=\"$instance\", type=~\"inputEror|inputDropped\", iface!=\"lo\"}[$__rate_interval]))",
       "legendFormat": "RX {{iface}}"
      },
      {
       "expr": "- sum by (iface) (rate(network_io_total{instance=\"$instance\", type=~\"outputEror|outputDropped\", iface!=\"lo\"}[$__rate_interval]))",
       "legendFormat": "TX {{iface}}"
      }
     ]
    },
    {
     "title": "Network transmissions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 6, "y": 25 },
     "targets": [
      {
       "expr": "rate(network_io_total{instance=\"$instance\", iface!=\"lo\", type=\"inputBytes\"}[$__rate_interval])/1024",
       "legendFormat": "RX {{iface}}"
      },
      {
       "expr": "-rate(network_io_total{instance=\"$instance\", iface!=\"lo\", type=\"outputBytes\"}[$__rate_interval])/1024",
       "legendFormat": "TX {{iface}}"
      }
     ]
    },
    {
     "title": "Network wlan current usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(network_io_total{instance=\"$instance\", iface=~\"$iface\", type=\"inputBytes\"}[$__rate_interval])/1024/1024*8",
       "legendFormat": "RX {{iface}} (mb/s)"
      },
      {
       "expr": "rate(network_io_total{instance=\"$instance\", iface=~\"$iface\", type=\"outputBytes\"}[$__rate_interval])/1024/1024*8",
       "legendFormat": "TX {{iface}} (mb/s)"
      }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "node_disk_read_bytes{instance=\"$instance\"}",
     "legendFormat": "READ {{dev}}"
    },
    {
     "expr": "- node_disk_written_bytes{instance=\"$instance\"}",
     "legendFormat": "WRITE {{dev}}"
    }
   ]
  },
  {
   "title": "Disks free space",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 14, "y": 26 },
   "targets": [
    {
     "expr": "node_filesystem_free{instance=\"$instance\", device=~\"^.+dev.+$\", fstype!=\"vfat\", type=\"percentage\"} * 100",
     "legendFormat": "{{device}} as {{fstype}} on {{mountpoint}} "
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 22, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-node_filesystem_free{instance=\"$instance\", device=~\"^.+dev.+$\", fstype!=\"vfat\", type=\"percentage\"}*100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk timings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "node_disk_read_time{instance=\"$instance\"}",
     "legendFormat": "READ {{dev}}"
    },
    {
     "expr": "- node_disk_write_time{instance=\"$instance\"}",
     "legendFormat": "WRITE {{dev}}"
    }
   ]
  }
 ]
}